spring.application.name=ecom-member
spring.main.web-application-type=reactive
spring.r2dbc.url=r2dbc:h2:mem:///ecom-member
spring.r2dbc.username=sa
spring.r2dbc.password=

springdoc.swagger-ui.path=/apispec.html
springdoc.swagger-ui.url=/apispec.yaml
springdoc.api-docs.enabled=true

spring.flyway.enabled=true
spring.flyway.url=jdbc:h2:mem:testdb;MODE=MySQL
spring.flyway.user=${spring.r2dbc.username}
spring.flyway.password=${spring.r2dbc.password}
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false

spring.messages.encoding=UTF-8